sudo: required
dist: trusty
addons:
  chrome: stable
  firefox: latest
language: node_js
node_js:
- '8'
cache:
  yarn: true
branches:
  except:
  - stable
before_install:
- export START_TIME=$( date +%s )
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm i -g yarn
install:
- yarn add @ckeditor/ckeditor5-dev-tests
- ckeditor5-dev-tests-install-dependencies
script:
- ckeditor5-dev-tests-travis
after_success:
- ckeditor5-dev-tests-save-revision
after_script:
- export END_TIME=$( date +%s )
- ckeditor5-dev-tests-notify-travis-status
env:
  global:
  - secure: 2B2J4L85DoU7hgeZdoczdDbq3M/MV45hZ1k+RngBq4Nb33JiqHJq4M9IvaJWmiFJijwoyKILPZc80B3JcJslb34+zoFTIVgvO/YRJLOdGj9hXHyfelt2uKO+jsGYE1DU/MLDwwzm0gguM0QoFMzo7OUTj80Rlp0BdH/yCIlsohv+A1b0avVOwsk4lkdasRr5xpRw0bTq/hzSTChCF4W2Z4ru7rD2hOew1EStKTVhSOhsZylaTgeRrghpdigsCAlGwxkd3CIdaGkfMP2V/NwRHU9d4rSVbkoQLJUanBXjVDPpILA1LwOW3JiLwBvEAlkc/9CNmWgSzlPrVNrBO4T2JqCzQhZ2/oBUbfId7ylKuRwvJsOObNlVdLs2w3zrSRY1T5RTYRUGCuPzecwsOYW3KRIcCp9r3PnUJ5O5fTD31uC6saMiHUbnDOqzRpu4ypp7eYm7ZmwIsN9T29pqly3m/XMEc7YdpsTyDd3A+mxNb2TcnyqbbBnzH6E/WMsjv/TLBYh897VaTAwCMtxFQ0CIPoYklXOH4E69TL54w2lK+W5NE5+1fPi/mULDfwB/eyQZ16iFLvCtsSDrc9US8TJm9QBrHhBzZA9KGo/TnJVNVg6R9J06IvixUHP+RZja7UbQ00gfRkCJc4fIGL47UjBNuhayhlR0GIJ1Bf1s/vjA7S0=
  - secure: qVBid2b/hiCAohgaF7S07xnvm4kVppS2tGniJ31RDTAVbYXcxnNJr69kHqLlAy9Fby2diOFxy0Td6lpyjFn1piqBTR5x32YN8P+SnFgrzKCCkOc3wCNmESaAPuVLrMAk6wxqyEvwhWpd2/bgZyK3LT3jE2vrvK9SQhM19TwyoBrVGyo5MiFANCtECN8SfCkj20Ndpc5Mj0P+ECg/0OQO4YiTq5vzQpV11hf/ElDLg3Q2KkoefBTYDo/FuuMvnTd14IZlKmNV+MQEazIWyygT4cAaaVuKpHTqzvkH419XvFJ4Bo4QxNsafCHH+AM+ryaAdiQ5D8qYRzbVLuDkKqXU2nkSZbxpK0St8s1WNofXDOXqfNKSQsJP4lWrvV4LMbshnxJGZEvbVN2fzaMl5mjS1MT2NES+wxW0vSdA4k2IagOELzeQGOAQ6WIePx0jE0yaLaM3wpZwwleITCOlEmpZ1VGgQDcQ9g2MFypDbmzXObmGpjc88AvvPAgyPozXr8DEn3nCViQtcnm42/kLMbc38Yca5fBBsXHpDMbQOFDk5qJIeDfLdxypExu4IMamqQ6zhCeW4M7IoRapLBZRHdA+K1KAYrYvDLMFbSf7c1QKGSXY+HJzeudzUKNRI80dgIoy4uzIbA4Z7ksUoQfJqINHUu5r5NFqOFJCfBF3o+5Fpoc=
  - secure: vICYvFKjvtC7r3i2N8PEf4/6pEcwa+6PbHRQJZFLLzRapuiEmRlregaDa4bQ6TwGCSiKQKZ3tAF2r8gLlgxptts0d6U/q3+HRJlvC6WwnACDzc6/lo2JtfP4no/20mFXF7hyq1M4VfuwNfQFMEPMUxTTXE06yKT6zUfxq3kZ8MK+sl9wX7nm++8Jo5Po8/YOqtFQrnTYbbAZhxOtyK5cULt7YBm7M1OXNRhbf1RMDc1Q11emY9d9AxXTYiucR6p2sl3++uIXndNkpA6ztR3p9gfKgBme4MIv7VyNAgZweq/mNdwjb3RucXaKbJXlegrQ31VaVwtzsSgoK2G8hiiyJffGg1EKPbdU852nspyr1rsxE9EfkZN8VBTK6uold1IzSADMybFV+Ed9Z37j3t1rUgei9f9S/u+DwctpoSWJ7J1TllW0pPewPO+aGIlqltEgl3fYBCKMQEHbHkaohA47wa2JRn87n5PHHd2QZCos5XWC31QcbirmR+1z4md5yTK3t2BK0TUUIkrE6JmfO5lf84w9rWJ+unCFVPjd0k534KjKcBPMKnRQUiTR8e2YR/PrPbydxd9SvX/7ujV/B+6/f672n/hdkXIDbicojbHAiFrdJBmIk86Ebb/j21PEfkOY1TQR9/J7a09SNsTK0Iup9MIC/VfWQZuQBboUPKig1jI=
